### ISSUE TITLE
Make Wheels Resizable

### ISSUE THREAD

**Issue by pngwen** [relowe/gradbot#14]
Make the wheels of the robot resizable in the builder screen. Note that this needs to have a realistic effect on the robot's movement in the simulator.

**Comment by samelfrink** [comment]
The wheels can now be resized via a toggle in the right bottom corner of the build tab screen. The wheels don't change in size visibly, but impact the speed of the robot. Note: as instructed, there is no limit on the wheel size parameter. However, increasing it significantly will essentially break the simulation as the robot goes too fast.
